# 由 tools/make_icons.py 生成，请勿手改
set(ICON_FILES
    resources/icons/close_secondary.svg
    resources/icons/close_primary.svg
    resources/icons/close_tertiary.svg
    resources/icons/close_white.svg
    resources/icons/close_danger.svg
    resources/icons/close_blue.svg
    resources/icons/disconnect_secondary.svg
    resources/icons/disconnect_primary.svg
    resources/icons/disconnect_tertiary.svg
    resources/icons/disconnect_white.svg
    resources/icons/disconnect_danger.svg
    resources/icons/disconnect_blue.svg
    resources/icons/doc_secondary.svg
    resources/icons/doc_primary.svg
    resources/icons/doc_tertiary.svg
    resources/icons/doc_white.svg
    resources/icons/doc_danger.svg
    resources/icons/doc_blue.svg
    resources/icons/folder_secondary.svg
    resources/icons/folder_primary.svg
    resources/icons/folder_tertiary.svg
    resources/icons/folder_white.svg
    resources/icons/folder_danger.svg
    resources/icons/folder_blue.svg
    resources/icons/gear_secondary.svg
    resources/icons/gear_primary.svg
    resources/icons/gear_tertiary.svg
    resources/icons/gear_white.svg
    resources/icons/gear_danger.svg
    resources/icons/gear_blue.svg
    resources/icons/grid_secondary.svg
    resources/icons/grid_primary.svg
    resources/icons/grid_tertiary.svg
    resources/icons/grid_white.svg
    resources/icons/grid_danger.svg
    resources/icons/grid_blue.svg
    resources/icons/local_secondary.svg
    resources/icons/local_primary.svg
    resources/icons/local_tertiary.svg
    resources/icons/local_white.svg
    resources/icons/local_danger.svg
    resources/icons/local_blue.svg
    resources/icons/pencil_secondary.svg
    resources/icons/pencil_primary.svg
    resources/icons/pencil_tertiary.svg
    resources/icons/pencil_white.svg
    resources/icons/pencil_danger.svg
    resources/icons/pencil_blue.svg
    resources/icons/play_secondary.svg
    resources/icons/play_primary.svg
    resources/icons/play_tertiary.svg
    resources/icons/play_white.svg
    resources/icons/play_danger.svg
    resources/icons/play_blue.svg
    resources/icons/plus_secondary.svg
    resources/icons/plus_primary.svg
    resources/icons/plus_tertiary.svg
    resources/icons/plus_white.svg
    resources/icons/plus_danger.svg
    resources/icons/plus_blue.svg
    resources/icons/refresh_secondary.svg
    resources/icons/refresh_primary.svg
    resources/icons/refresh_tertiary.svg
    resources/icons/refresh_white.svg
    resources/icons/refresh_danger.svg
    resources/icons/refresh_blue.svg
    resources/icons/restart_secondary.svg
    resources/icons/restart_primary.svg
    resources/icons/restart_tertiary.svg
    resources/icons/restart_white.svg
    resources/icons/restart_danger.svg
    resources/icons/restart_blue.svg
    resources/icons/search_secondary.svg
    resources/icons/search_primary.svg
    resources/icons/search_tertiary.svg
    resources/icons/search_white.svg
    resources/icons/search_danger.svg
    resources/icons/search_blue.svg
    resources/icons/server_secondary.svg
    resources/icons/server_primary.svg
    resources/icons/server_tertiary.svg
    resources/icons/server_white.svg
    resources/icons/server_danger.svg
    resources/icons/server_blue.svg
    resources/icons/terminal_secondary.svg
    resources/icons/terminal_primary.svg
    resources/icons/terminal_tertiary.svg
    resources/icons/terminal_white.svg
    resources/icons/terminal_danger.svg
    resources/icons/terminal_blue.svg
    resources/icons/trash_secondary.svg
    resources/icons/trash_primary.svg
    resources/icons/trash_tertiary.svg
    resources/icons/trash_white.svg
    resources/icons/trash_danger.svg
    resources/icons/trash_blue.svg
    resources/icons/upload_secondary.svg
    resources/icons/upload_primary.svg
    resources/icons/upload_tertiary.svg
    resources/icons/upload_white.svg
    resources/icons/upload_danger.svg
    resources/icons/upload_blue.svg
)
